short_description: >
  blktests is a test framework for the Linux kernel block layer and storage stack.

description: >
 It is inspired by the xfstests filesystem testing framework. 
 It was originally written by Omar Sandoval and announced in 2017.

homepage: https://github.com/osandov/blktests

parameters:
 test:
 nvme_trtype:
 use_siw:

