short_description: >
 Persistent Memory Development Kit

description: >
 The Persistent Memory Development Kit (PMDK) is a collection of libraries and tools for System Administrators and Application Developers to simplify managing and accessing persistent memory devices. For more information, see https://pmem.io.

homepage: https://github.com/pmem/pmdk

parameters:

results:

