short_description: >
 BZIP2 is a parallel implementation of the bzip2 block-sorting file compressor that uses pthreads and achieves near-linear speedup on SMP machines. The output of this version is fully compatible with bzip2 v1.0.2 or newer (ie:anything compressed with pbzip2 can be decompressed with bzip2). PBZIP2 should work on any system that has a pthreads compatible C++ compiler (such as gcc).

description: >

homepage: https://launchpad.net/pbzip2

parameters:
 runtime:
 nr_threads:
 blocksize:
 iterations:

results:

