short_description: >
 OpenSSL is a robust, commercial-grade, full-featured Open Source Toolkit for the TLS (formerly SSL), DTLS and QUIC (currently client side only) protocols.

description: >
 The protocol implementations are based on a full-strength general purpose cryptographic library, which can also be used stand-alone. Also included is a cryptographic module validated to conform with FIPS standards.OpenSSL is descended from the SSLeay library developed by Eric A. Young and Tim J. Hudson.The official Home Page of the OpenSSL Project is www.openssl.org.

homepage: https://github.com/openssl/openssl.git

parameters:
 runtime:
 algorithm:

results:
 openssl-speed.sign_per_sec:
 openssl-speed.verify_per_sec: 
 openssl-speed.16_size_block_Kbps: 
 openssl-speed.64_size_block_Kbps: 
 openssl-speed.256_size_block_Kbps: 
 openssl-speed.1024_size_block_Kbps: 
 openssl-speed.8192_size_block_Kbps: 
 openssl-speed.16384_size_block_Kbps: 

