short_description: >
 Suite of real-time tests - cyclictest, hwlatdetect, pip_stress, pi_stress, pmqtest, ptsematest, rt-migrate-test, sendme, signaltest, sigwaittest, svsematest.

description: >	

homepage: https://git.kernel.org/pub/scm/utils/rt-tests/rt-tests

parameters: 
 priority：
 clock：
 interval：
 histogram：
 loops：

results:

