short_description: >
 LZ4 - Extremely fast compression

description: >
 LZ4 is lossless compression algorithm, providing compression speed > 500 MB/s per core, scalable with multi-cores CPU. It features an extremely fast decoder, with speed in multiple GB/s per core, typically reaching RAM speed limits on multi-core systems.

 Speed can be tuned dynamically, selecting an "acceleration" factor which trades compression ratio for faster speed. On the other end, a high compression derivative, LZ4_HC, is also provided, trading CPU time for improved compression ratio. All versions feature the same decompression speed.

 LZ4 is also compatible with dictionary compression, both at API and CLI levels. It can ingest any input file as dictionary, though only the final 64KB are used. This capability can be combined with the Zstandard Dictionary Builder, in order to drastically improve compression performance on small files.

 LZ4 library is provided as open-source software using BSD 2-Clause license.

homepage: https://github.com/lz4/lz4/

parameters:
 compression:
 iterations:

results:
 lz4-test.compression_level: 
 lz4-test.compression_MB_per_sec: 
 lz4-test.decompression_MB_per_sec: 
